apiVersion: v1
kind: Service
metadata:
  name: backend-svc
  labels:
    {{- include "youtube-manager.labels" . | nindent 4 }}
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
