{{- if .Values.redis.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  labels:
    {{- include "youtube-manager.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.redis.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.redis.storage | quote }}
{{- end }}
